 <template>
  <section>
    <div class="line">
      <card :info="info.broadcast" class="card-multi">
        <template slot="nodeContent">
          <bar :bar-style="barStyle" :list="percents"></bar>
        </template>
      </card>
      <card :info="info.nodePosition" class="card-multi mt">
        <template slot="nodeContent">
          <w-map :list="mapList"></w-map>
        </template>
      </card>
    </div>
    <div class="text__outer-link">
      <a 
        :href="outerLink.url" 
        target="_blank">
        {{ outerLink.name }}
        <img src="~/assets/images/arrow_forward.svg"/>
      </a>
    </div>
  </section>
</template>

<script type="text/babel">

import card from './card.vue';
import Bar from './Bar.vue';
import WMap from './WMap.vue';

export default {
  components: {
    card,
    Bar,
    WMap
  },
  computed: {
    info() {
      return {
        broadcast: {
          img: require('~/assets/images/product/supernode.svg'),
          title: this.$t('products.platform.supernode.title'),
          titleData: '96%',
          rightLink: 'https://explorer.vite.net/FullNode'
        },
        nodePosition: {
          img: require('~/assets/images/product/fullnode.svg'),
          title: this.$t('products.platform.fullnode.title'),
          titleData: '1047',
          rightLink: 'https://explorer.vite.net/FullNode'
        },
        
      };
    }
  },
  data: function () {
    return {
      barStyle: {
        width: '100%',
        height: '315px',
        marginTop: '0px',
        marginLeft: '0px'
      },
      percents: [{'count':17,'item':'100'},{'count':10,'item':'99.9'},{'count':4,'item':'99.5'},{'count':2,'item':'99.0'},{'count':3,'item':'95.0'},{'count':1,'item':'90.0'},{'count':1,'item':'60.0'},{'count':1,'item':'10.0'},{'count':1,'item':'0.0'}],
      mapList:[
        {
          'city': 'Nanjing',
          'count': 817,
          'lat': 32.0617,
          'lng': 118.7778,
          'nodeNames': [
            'vitegood',
            'vite-lj-node',
            'vite-19',
            'LDT-14',
            'Mike-06',
            'vite-novy-node-3',
            'N4Y',
            'vite-16',
            'vite-tly-1',
            'vvktk18',
            'vite003',
            'VM_NODE',
            'vite-full-node-nm-009',
            'LDT-07',
            'vite-full-node-nm-003',
            'algato-fn18',
            'adiHetznerCosmin',
            'algato-fn10',
            'javinjunfeng-ali',
            'SwissVite.org',
            'leogo1',
            'Apollo-24',
            'algato-fn01',
            'Apollo-04',
            'vite-26',
            'vite-full-node',
            'Apollo-03',
            'StanzillaG02',
            'Apollo-06',
            'New-01',
            'vite.plus',
            'ogktk4',
            'Apollo-01',
            'vite-databus-2',
            'Mike-07',
            'fine-fine-node',
            'ogktk5',
            'vite-13',
            'vite-22',
            'LDT-12',
            'vite-29',
            'vite-full-node',
            'zz_tcc_dd1',
            'Mike-01',
            'ogktk9',
            'vite-full-node',
            'ogktk10',
            'Panos-12',
            'LDT-03',
            'vite-full-node',
            'vite-351',
            'vite-213-23',
            'vite-full-node',
            'vite-31',
            'Mike-02',
            'Apollo-17',
            'loopring-node',
            'vite-leokaza3',
            'LDT-02',
            'Opt-10',
            'vite-full-node-nm-010',
            'CandySky',
            'vite-full-node',
            'algato-fn09',
            'LDT-13',
            'Apollo-19',
            'LDT-01',
            'vite-love-node',
            'viteboy',
            'explorer',
            'vite-41',
            'Turbo-6',
            'Apollo-02',
            'luhe03',
            'algato-fn04',
            'LDT-09',
            'Apollo-11',
            'vite-full-node-nm-007',
            'demon-hunter',
            'zz_tcc_dm1',
            'algato-fn24',
            'vite-18',
            'vite-full-node',
            'Panos-08',
            'Apollo-05',
            'YoLo',
            'vite-20',
            'algato-fn26',
            'vt_cm64_4_51_09efe5d6',
            'algato-fn14',
            'ogktk6',
            'bibabo-super-node',
            'algato-fn23',
            'Apollo-08',
            'vite-full-node',
            'vite-full-node',
            'Mike-08',
            'vite-full-node',
            'vite-frank-node',
            'algato-fn17',
            'New-05',
            'algato-fn08',
            'xiaojinge',
            'vite-novy-node-4',
            'LDT-06',
            'Bite',
            'vite-full-node-nm-008',
            'Panos-03',
            'vvktk15',
            'vite-42',
            'ogktk8',
            'vite-sunny-node',
            'vite-full-node',
            'algato-fn19',
            'LDT-04',
            'vite-21',
            'vite-full-node',
            'vite-27',
            'ogktk7',
            'Apollo-23',
            'vite-vasylych1',
            'vite-full-node-nm-005',
            '# 001',
            'leogo1',
            'algato-fn25',
            'MrFox-full-node-eos2',
            'vite-full-node',
            'vite-full-node-nm-002',
            'algato-fn02',
            'Panos-02',
            'Apollo-07',
            'yad2',
            'MrFox-full-node-eos3',
            'vite-RA-SsS-',
            'Mike-04',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node-nm-006',
            'vite-RA-AbA-',
            'vite-dragon-awesome',
            'vite-full-node-nm-004',
            'beauty_vite_48',
            'vite-full-node-nm-011',
            'Apollo-22',
            'algato-fn22',
            'Mike-09',
            'Panos-04',
            'algato-fn03',
            'algato-fn15',
            'algato-fn20',
            'algato-fn05',
            'vite-slpslpslp',
            'zz_tc2',
            'leonidnode6',
            'leogo1',
            'Mike-05',
            'Stanzilla',
            'Apollo-20',
            'vite-full-node',
            'vite-tly-7',
            'CYP-9',
            'Turbo-7',
            'Turbo-2',
            'Apollo-18',
            'leogo1',
            'Cool-1',
            'Panos-11',
            'ARTvps1a2',
            'ARTvps8a4',
            'ARTvps11a4',
            'IC_Node',
            'vite-RA-',
            'Hot-8',
            'aiyh02',
            'algato-fn16',
            'algato-fn07',
            'vite-RA-ApA-',
            'Set-3',
            'Mike-03',
            'Apollo-12',
            'LDT-05',
            'Apollo-10',
            'LDT-11',
            'Apollo-16',
            'New-11',
            'algato-fn13',
            'CYP-6',
            'algato-fn21',
            'Mike-1',
            'nitro-9c6ff50f',
            'hydro-d3ac0f46',
            'nitro-a82fa403',
            'hydro-8b9fdf81',
            'nitro-ea2e3e10',
            'nitro-85024bac',
            'nitro-985b4fb2',
            'hydro-1afcb6ba',
            'hydro-57e5f3e6',
            'hydro-901eaed1',
            'hydro-319d93be',
            'nitro-8dcb2640',
            'nitro-b763cba0',
            'hydro-60e4f9f3',
            'nitro-faa5a9c7',
            'hydro-d037fa10',
            'nitro-8dcd48bd',
            'nitro-8583e908',
            'hydro-1deadd1a',
            'hydro-2f25608c',
            'nitro-eb5b3b9d',
            'nitro-458ad359',
            'nitro-06b0a480',
            'nitro-f1fcda3c',
            'hydro-258ce023',
            'nitro-3f71eeec',
            'hydro-f6c090a4',
            'hydro-1497a0bb',
            'nitro-f0f257b3',
            'hydro-9e674b5a',
            'nitro-3aedbb37',
            'hydro-dc42554a',
            'nitro-f2563ee1',
            'hydro-5b7ccca1',
            'nitro-d6a0f44a',
            'nitro-89f6d9b9',
            'hydro-80e3e842',
            'asym-th',
            'hydro-0c3bf6c8',
            'nitro-bb474eb6',
            'nitro-8bae4fcf',
            'nitro-38c7c6bd',
            'nitro-0b629ae0',
            'hydro-37d051c2',
            'nitro-56c700e2',
            'nitro-e0471522',
            'Enter-9',
            'ARTvps7a4',
            'Love-07',
            'hydro-f69f4ce8',
            'LDT-08',
            'Super-8',
            'vite-RA-AcA-',
            'vite-RA-A3A-',
            'vite-RA-AyA-',
            'vite-RA-AzA-',
            'Red-1',
            'Apollo-15',
            'Apollo-14',
            'vite-leonad3',
            'Set-4',
            'Opt-7',
            'zz_alc_dd',
            'Apollo-25',
            'Love-08',
            'vitetisworker0219',
            'Love-02',
            'Super-1',
            'Enter-1',
            'vite-tly-4',
            'Love-06',
            'Apollo-21',
            'Yes-18',
            'Turbo-9',
            'Turbo-4',
            'Super-4',
            'vite-24',
            'ogktk3',
            'ogktk1',
            'leogo1',
            'zz_tcc_sc1',
            'Panos-06',
            'Love-10',
            'zz_wy_alc',
            'vite-RA-A4A-',
            'vite-RA-A7A-',
            'Opt-4',
            'vite-RA-A8A-',
            'Apollo-09',
            'Apollo-13',
            'Hot-6',
            'Mike-2',
            'viteyou',
            'vite-RA-AsA-',
            'LDT-00',
            'Mike-6',
            'Opt-9',
            'Love-05',
            'Mike-7',
            'Turbo-5',
            'vite-RA-AmA-',
            'vite-novy-node-5',
            'CYP-1',
            'Turbo-10',
            'Opt-1',
            'cala01',
            'ty_vite_server',
            'vite-YuriyK6',
            'vite-YuriyK8',
            'vite-YuriyK9',
            'algato-fn12',
            'vite-YuriyK14',
            'vite-YuriyK10',
            'vite-YuriyK11',
            'vite-YuriyK7',
            'vite-YuriyK13',
            'vite-RA-AhA-',
            'rinapavlovna',
            'leogo1',
            'vite-novy-node-2',
            'yad1',
            'CYP-8',
            'vite-RA-AnA-',
            'LDT-10',
            'Opt-5',
            'CYP-2',
            'CYP-3',
            'vite-novy-node-6',
            'CYP-4',
            'Mike-3',
            'Super-10',
            'Enter-7',
            'Mike-4',
            'n4103',
            'n4102',
            'CYP-7',
            'CYP-5',
            'Super-5',
            'leogo1',
            'Turbo-1',
            'Cool-6',
            'vite-full-node',
            'Alt-8',
            'vite-RA-A9A-',
            'Alt-1',
            'Cool-3',
            'Love-11',
            'vite-RA-A2A-',
            'leogo1',
            'Enter-4',
            'Cool-8',
            'Panos-05',
            'vite-RA-AkA-',
            'Super-3',
            'Hot-10',
            'vite-tly-3',
            'Love-12',
            'leogo1',
            'Opt-8',
            'Super-2',
            'Super-7',
            'vite-ol2',
            'Red-2',
            'aiyh01',
            'vite555',
            'vite-RA-AoA-',
            'vite-viter2',
            'Alt-10',
            'vite-gal1',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'Mike-8',
            'vite-RA-A11A-',
            'primus',
            'vite-dar1',
            'vite-f1',
            'vite-RA-AaA-',
            'vite-nor2',
            'vite-full-mar1',
            'Set-5',
            'Hot-7',
            'vite-full-node',
            'Mike-5',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'leogo1',
            'vite-full-node',
            '# 003',
            'vite-full-node',
            'vite-RA-AdA-',
            'algato-fn11',
            'vite-full-node',
            'vite-RA-BbB-',
            'CYP-10',
            'vite-full-node',
            'vite-14',
            'Turbo-3',
            'algato-fn06',
            'vite-RA-AiA-',
            'Red-9',
            'Yes-00',
            'Red-10',
            'Yes-14',
            'Red-7',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'Cool-5',
            'vite-full-node',
            'vite-full-node',
            'Yes-06',
            'vite-full-node',
            'Yes-01',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'Yes-15',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'Mike-9',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'Yes-13',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'Yes-10',
            'Yes-09',
            'leonidnode4',
            'Red-5',
            'bulka02',
            'vite-full-node',
            'vite-RA-A12A-',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'leogo1',
            'vite-full-node',
            'vite-full-node',
            'bulka',
            'Yes-19',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'Yes-12',
            'Yes-05',
            'Yes-17',
            'Opt-3',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'Yes-16',
            'mayka',
            'Yes-03',
            'Alt-2',
            'vite-full-node',
            'Panos-10',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'Red-3',
            'Red-8',
            'Yes-02',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'mike-vite',
            'Yes-07',
            'Yes',
            'Red-6',
            'Yes-08',
            'Yes-04',
            'Red-4',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'bulka03',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'Yes-11',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'Mike-0',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'Super-9',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'asym-rpi',
            'New-27',
            'vite-full-node',
            'fire-5f205011',
            'fire-eb2d4945',
            'Panos-01',
            'fire-8720ce4f',
            'fire-359535f5',
            'fire-7b7d456a',
            'fire-48b596ae',
            'vite-full-node',
            'fire-36733ce7',
            'fire-2049ae92',
            'fire-a3278f2f',
            'fire-170a5b6c',
            'fire-0fb1a6b0',
            'fire-fa9ccf01',
            'fire-c1e54883',
            'vite-full-node',
            'fire-244ce1c9',
            'fire-2beb6a01',
            'fire-b1a11f83',
            'fire-84754c03',
            'vite-full-node',
            'vite-full-node',
            'hydro-cfdae7ed',
            'hydro-dc42554a',
            'hydro-258ce023',
            'hydro-2f25608c',
            'hydro-739ba05e',
            'vite-full-node',
            'hydro-1deadd1a',
            'hydro-e9c5c38a',
            'hydro-d6a76acd',
            'hydro-8b9fdf81',
            'hydro-37d051c2',
            'hydro-5834e201',
            'hydro-0c3bf6c8',
            'leogo1',
            'hydro-9e674b5a',
            'hydro-d037fa10',
            'hydro-1afcb6ba',
            'hydro-80e3e842',
            'hydro-5b7ccca1',
            'hydro-1497a0bb',
            'hydro-901eaed1',
            'hydro-bd70c042',
            'hydro-447ff5a7',
            'hydro-d3ac0f46',
            'hydro-f69f4ce8',
            'hydro-57e5f3e6',
            'hydro-f6c090a4',
            'hydro-9c9c791d',
            'hydro-319d93be',
            'hydro-09a786e5',
            'hydro-60e4f9f3',
            'hydro-607e7903',
            'hydro-2e00cc8f',
            'nitro-f1fcda3c',
            'nitro-7e0354aa',
            'nitro-bb474eb6',
            'nitro-ea2e3e10',
            'nitro-3aedbb37',
            'nitro-9c6ff50f',
            'nitro-faa5a9c7',
            'nitro-8bae4fcf',
            'nitro-f0f257b3',
            'nitro-3e97da4d',
            'nitro-36f22493',
            'nitro-85024bac',
            'nitro-f2563ee1',
            'nitro-985b4fb2',
            'vite-full-node',
            'vite-full-node',
            'nitro-0b629ae0',
            'nitro-0942c796',
            'vite-full-node',
            'nitro-56c700e2',
            'nitro-38c7c6bd',
            'nitro-eb03ce1b',
            'nitro-3f71eeec',
            'nitro-6ba540cc',
            'nitro-3ca19b8f',
            'nitro-d76f53bd',
            'nitro-6d56afb2',
            'nitro-261ba524',
            'nitro-d6a0f44a',
            'nitro-89f6d9b9',
            'nitro-b763cba0',
            'nitro-8dcb2640',
            'vite-tly-5',
            'nitro-458ad359',
            'nitro-06b0a480',
            'leogo1',
            'nitro-e0471522',
            'nitro-8583e908',
            'nitro-a82fa403',
            'vite-full-node',
            'nitro-8dcd48bd',
            'nitro-eb5b3b9d',
            'nitro-4f9892af',
            'nitro-4159db22',
            'hetz-1',
            'nitro-7d991f76',
            'nitro-6c90a7a9',
            'hydro-f725154f',
            'hydro-f8e0eba5',
            'hydro-3ecb44f4',
            'hydro-b8ebdb7d',
            'hydro-604546f1',
            'hydro-c88fd394',
            'hydro-969ed226',
            'hydro-272e8121',
            'hydro-5b6bc6ae',
            'hydro-e369fc63',
            'hydro-6c1c95ee',
            'hydro-ec8f900a',
            'hydro-67c510c3',
            'hydro-4a8019b5',
            'hydro-c7794b9d',
            'hydro-7a471004',
            'hydro-a4105144',
            'hydro-e7d2e989',
            'hydro-320f2c09',
            'hydro-d1aa24e6',
            'hydro-cd745526',
            'hydro-b7d28b44',
            'hydro-151fa06d',
            'hydro-56c11525',
            'hydro-9e2f5287',
            'hydro-407f5ba8',
            'New-16',
            'hydro-1f73e778',
            'vite-full-node',
            'hydro-0d4dcc7a',
            'hydro-e4cbc650',
            'hydro-3354a5a9',
            'hydro-b5fe9543',
            'Opt-2',
            'hydro-4e864c45',
            'hydro-0ce9079e',
            'hydro-6663288e',
            'hydro-5bbf0583',
            'hydro-1f570c97',
            'hydro-2ccdc61a',
            'hydro-97e90795',
            'hydro-8637fc69',
            'hydro-d0d2cb00',
            'vite-full-node',
            'hydro-ba7fac26',
            'hydro-8e40ae8c',
            'hydro-044fae98',
            'hydro-5cb197de',
            'hydro-ea54b6a6',
            'nitro-898b9da8',
            'nitro-9143a2a0',
            'nitro-97b7c038',
            'New-17',
            'nitro-6d0c07e8',
            'nitro-ada8c66f',
            'nitro-407be2bb',
            'nitro-d5635050',
            'nitro-dffedf6a',
            'nitro-0022da61',
            'nitro-5698e71c',
            'nitro-01682703',
            'nitro-3ba3ce95',
            'nitro-add96148',
            'nitro-d674b5c4',
            'nitro-1f83eb14',
            'nitro-b2001857',
            'nitro-5f845c17',
            'nitro-e569f4a9',
            'nitro-43ab3503',
            'nitro-ebf8b371',
            'nitro-3bf53877',
            'nitro-049ef429',
            'Super-9',
            'nitro-34333374',
            'nitro-76d596b1',
            'nitro-5473ddb6',
            'nitro-ecc03a9f',
            'nitro-ca9e415d',
            'nitro-150d9ff3',
            'vite-full-node',
            'nitro-c987b21d',
            'vite-full-node',
            'nitro-98190c7f',
            'nitro-d8e22a08',
            'nitro-86e33243',
            'nitro-f4a4100a',
            'nitro-af242535',
            '501a9080',
            '26e8c665',
            '264eee82',
            '4c51b011',
            'ad810544',
            'vite-full-node',
            'aaa8e4ac',
            '6fce40d1',
            '6ae1206a',
            'vite-full-node',
            'vite-full-node',
            '512fc9d1',
            '6e9c2eef',
            '1195f008',
            'a77c8263',
            'vite-full-node',
            'vite-full-node',
            'New',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node'
          ]
        },
        {
          'city': 'St Helens',
          'count': 1,
          'lat': 53.4172,
          'lng': -2.7109,
          'nodeNames': [
            'ViteMNR3'
          ]
        },
        {
          'city': 'Potsdam',
          'count': 1,
          'lat': 52.403,
          'lng': 13.0626,
          'nodeNames': [
            'Jacks2-vite-full-node'
          ]
        },
        {
          'city': 'Dublin',
          'count': 1,
          'lat': 53.3331,
          'lng': -6.2489,
          'nodeNames': [
            'vite-1'
          ]
        },
        {
          'city': 'Boardman',
          'count': 1,
          'lat': 45.8491,
          'lng': -119.7143,
          'nodeNames': [
            'vite-4'
          ]
        },
        {
          'city': 'Slough',
          'count': 56,
          'lat': 51.5353,
          'lng': -0.6658,
          'nodeNames': [
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node'
          ]
        },
        {
          'city': 'Tokyo',
          'count': 5,
          'lat': 35.685,
          'lng': 139.7514,
          'nodeNames': [
            'vite-5',
            'Masa5-full-node',
            'Masa4-full-node',
            'Masa3-full-node',
            'Masa2-full-node'
          ]
        },
        {
          'city': 'Frankfurt am Main',
          'count': 26,
          'lat': 50.1153,
          'lng': 8.6823,
          'nodeNames': [
            'zz_dojz_7_20',
            'zz_dojz_9_164',
            'vite-9',
            'zz_dojz_3_37',
            'zz_dojz_4_19',
            'kitsune-k03',
            'kitsune-k02',
            'zz_dojz_10_51',
            'zz_dojz_8_182',
            'zz_dohmhmvwan9_15',
            'zz_dohmhmvwan5_205',
            'zz_dohmhmvwan4_42',
            'zz_dohmhmvwan2_75',
            'zz_dohmhmvwan3_137',
            'zz_dohmhmvwan10_141',
            'zz_dohmhmvwan1_146',
            'zz_dohmhmvwan7_72',
            'zz_dohmhmvwan6_2',
            'zz_dohmhmvwan8_188',
            'zz_dojz_5_198',
            'zz_dojz_6_76',
            'zz_dojz_2_183',
            'zz_dojz_1_147_596298d6',
            'vite-full-node',
            'Beautiful-08',
            'kitsune-k10'
          ]
        },
        {
          'city': 'Haarlem',
          'count': 45,
          'lat': 52.3613,
          'lng': 4.6464,
          'nodeNames': [
            'hydro-41817bec',
            'hydro-54fc21ae',
            'hydro-9fcefff6',
            'hydro-63da7ac5',
            'hydro-33694220',
            'hydro-33eb63d2',
            'hydro-a11d3936',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'fire-b7909458',
            'fire-fd6a5052',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'hydro-54fc21ae',
            'hydro-63da7ac5',
            'vite-full-node',
            'hydro-f5a40975',
            'hydro-33694220',
            'hydro-41817bec',
            'vite-full-node',
            'hydro-1beedfba',
            'hydro-a11d3936',
            'hydro-9fcefff6',
            'hydro-33eb63d2',
            'vite-full-node',
            'hydro-f9988ce7',
            'hydro-dbcff735',
            'hydro-8ff492dc',
            'hydro-f326bc89',
            'hydro-971d489c',
            'hydro-e8e00dcc',
            'hydro-64cb4586',
            'hydro-301c1d2b',
            'hydro-0284da54',
            'hydro-3ace3332',
            'hydro-5fcea98b',
            'hydro-6206ac25',
            'hydro-fbacc37f',
            'hydro-cf8c5e42',
            'hydro-3f06a081',
            'vite-full-node',
            'vite-full-node'
          ]
        },
        {
          'city': 'Arezzo',
          'count': 81,
          'lat': 43.4628,
          'lng': 11.8807,
          'nodeNames': [
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'ViteCH',
            'vite-full-node',
            'ViteCH',
            'Vite.Casino',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'nodecap1',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node'
          ]
        },
        {
          'city': 'Wrocław',
          'count': 9,
          'lat': 51.0957,
          'lng': 17.0176,
          'nodeNames': [
            'vite-RA-AxA-',
            'vite-RA-ArA-',
            'vite-RA-FgF-',
            'vite-RA-A10A-',
            'vite-RA-AjA-',
            'vite-RA-A5A-',
            'vite-RA-ABS-',
            'vite-RA-A6A-',
            'vite-RA-AtA-'
          ]
        },
        {
          'city': 'Buffalo',
          'count': 24,
          'lat': 42.8864,
          'lng': -78.8781,
          'nodeNames': [
            'Bit-6',
            'asym-us3',
            'asym-us1',
            'asym-us2',
            'Awesome-01',
            'Bit-2',
            'Bit',
            'Awesome-08',
            'Awesome-02',
            'Awesome-09',
            'Awesome-04',
            'Awesome-07',
            'Bit-1',
            'Awesome-11',
            'Awesome-00',
            'Awesome-03',
            'Awesome-05',
            'Bit-4',
            'Awesome-06',
            'N11Pit',
            'Bit-5',
            'Bit-3',
            'Bit-7',
            'Awesome-10'
          ]
        },
        {
          'city': 'Shenzhen',
          'count': 1,
          'lat': 22.5333,
          'lng': 114.1333,
          'nodeNames': [
            '# 005'
          ]
        },
        {
          'city': 'Munich',
          'count': 3,
          'lat': 48.1089,
          'lng': 11.6074,
          'nodeNames': [
            'Michalis101',
            'vite-super',
            'Harriet'
          ]
        },
        {
          'city': 'St Petersburg',
          'count': 3,
          'lat': 59.8944,
          'lng': 30.2642,
          'nodeNames': [
            'ARTvpsa1',
            'n41_p',
            'n4101'
          ]
        },
        {
          'city': 'Bengaluru',
          'count': 20,
          'lat': 12.9833,
          'lng': 77.5833,
          'nodeNames': [
            'zz_docm15910_85',
            'zz_docm1593_224',
            'zz_docm1596_195',
            'zz_docm1597_65',
            'zz_docm1591_43',
            'zz_docm1592_227',
            'zz_docm1595_40',
            'tanuki-04',
            'zz_docm1599_216',
            'tanuki-07',
            'tanuki-01',
            'tanuki-06',
            'tanuki-02',
            'zz_docm1592_236',
            'tanuki-05',
            'tanuki-03',
            'tanuki-10',
            'zz_docm1598_139',
            'tanuki-08',
            'Beautiful-10'
          ]
        },
        {
          'city': 'Clifton',
          'count': 2,
          'lat': 40.8344,
          'lng': -74.1377,
          'nodeNames': [
            'Beautiful-02',
            'Amazing-09'
          ]
        },
        {
          'city': 'Akiruno',
          'count': 1,
          'lat': 35.7333,
          'lng': 139.4833,
          'nodeNames': [
            'vite-Japan-node'
          ]
        },
        {
          'city': 'Lakewood',
          'count': 1,
          'lat': 33.8473,
          'lng': -118.1115,
          'nodeNames': [
            'abyscuit-node'
          ]
        },
        {
          'city': 'Aveiro',
          'count': 1,
          'lat': 40.6443,
          'lng': -8.6455,
          'nodeNames': [
            'vite-full-node-nm-001'
          ]
        },
        {
          'city': 'Beijing',
          'count': 9,
          'lat': 39.9288,
          'lng': 116.3889,
          'nodeNames': [
            '# 002',
            'zz_tc_ff2',
            'vite-38',
            'lnking-full-node',
            'javinjunfeng-tx',
            'sagewolf-full-node',
            'zz_tcc_xm1',
            'zz_tc_wy',
            'vite-full-node-amds'
          ]
        },
        {
          'city': 'Perm',
          'count': 4,
          'lat': 58,
          'lng': 56.25,
          'nodeNames': [
            'vite-YuriyK3',
            'vite-YuriyK5',
            'vite-YuriyK2',
            'vite-YuriyK1'
          ]
        },
        {
          'city': 'Changde',
          'count': 1,
          'lat': 29.0464,
          'lng': 111.6783,
          'nodeNames': [
            'vite-full-node'
          ]
        },
        {
          'city': 'Oftering',
          'count': 1,
          'lat': 48.234,
          'lng': 14.1357,
          'nodeNames': [
            'luhe02'
          ]
        },
        {
          'city': 'London',
          'count': 16,
          'lat': 51.5353,
          'lng': -0.6658,
          'nodeNames': [
            'zz_dobov_9_29',
            'zz_dobov_6_118',
            'zz_dobov_4_114',
            'zz_dobov_8_206',
            'zz_dobov_1_31_e0e5c4a9',
            'zz_dobov_5_185',
            'zz_dobov_7_17',
            'zz_dobov_10_132',
            'zz_dobov_3_195',
            'zz_dobov_2_167',
            'Amazing-05',
            'Blue-1',
            'Amazing-04',
            'Beautiful-06',
            'Amazing-01',
            'Beautiful-07'
          ]
        },
        {
          'city': 'Columbus',
          'count': 1,
          'lat': 39.9653,
          'lng': -83.0235,
          'nodeNames': [
            'CONTACT SWISSVITE FOR NODE MONITORING SOLUTIONS'
          ]
        },
        {
          'city': 'North Bergen',
          'count': 21,
          'lat': 40.7939,
          'lng': -74.0258,
          'nodeNames': [
            'zz_docmwg168_9_10',
            'zz_dowf_7_199',
            'zz_dowf_4_11',
            'zz_dowf_1_93_6fad0bfc',
            'zz_docmwg168_5_203',
            'zz_dowf_9_108',
            'zz_dowf_8_65',
            'zz_dowf_10_226',
            'zz_dowf_5_192',
            'zz_dowf_2_241',
            'zz_docmwg168_3_235',
            'zz_dowf_3_128',
            'zz_dowf_6_49',
            'zz_docmwg168_2_156',
            'vite-Sea50',
            'zz_docmwg168_1_75_475b2b1f',
            'vite-Sea53',
            'vite-Sea58',
            'vite-Ocean02',
            'vite-Sea59',
            'vite-Sea62'
          ]
        },
        {
          'city': 'Jamaica',
          'count': 1,
          'lat': 40.6763,
          'lng': -73.7966,
          'nodeNames': [
            'DarkChain'
          ]
        },
        {
          'city': 'Kawasaki',
          'count': 1,
          'lat': 35.6203,
          'lng': 139.5446,
          'nodeNames': [
            'Masa-full-node'
          ]
        },
        {
          'city': 'Atlantic',
          'count': 1,
          'lat': 41.4003,
          'lng': -95.0101,
          'nodeNames': [
            'satans-full-node'
          ]
        },
        {
          'city': 'Toronto',
          'count': 13,
          'lat': 43.6555,
          'lng': -79.3626,
          'nodeNames': [
            'zz_dosf7_15',
            'zz_dosf2_171',
            'zz_dosf3_45',
            'zz_dosf9_224',
            'zz_dosf10_249',
            'zz_dosf4_167',
            'zz_dosf8_71',
            'zz_dosf_1_97_697014c4',
            'zz_dosf6_2',
            'zz_dosf5_156',
            'vite-Ocean01',
            'Beautiful-09',
            'Amazing-02'
          ]
        },
        {
          'city': 'Sydney',
          'count': 3,
          'lat': -33.8612,
          'lng': 151.1982,
          'nodeNames': [
            'vite-10',
            'ovh-3',
            'ovh-4'
          ]
        },
        {
          'city': 'Mountain View',
          'count': 29,
          'lat': 37.4056,
          'lng': -122.0775,
          'nodeNames': [
            'vvktk11',
            'vvktk13',
            'vite-full-node',
            'slay-full-node',
            'ak-full-node',
            'vvktk12',
            'vvktk17',
            'GCP-full-node',
            'ogktk2',
            'vite-fonzie',
            'Panos-09',
            'vite.vip.sbp',
            'Love-01',
            'Love-03',
            'vvktk16',
            'vvktk14',
            'Love-04',
            'Love-09',
            'leogo1',
            'naktk1',
            'rina',
            'vite-YuriyK15',
            'vite-YuriyK12',
            'leogo1',
            'leogo1',
            'leogo1',
            'Panos-07',
            'vite-tor1',
            'vite-iva1'
          ]
        },
        {
          'city': 'Ashburn',
          'count': 2,
          'lat': 39.0481,
          'lng': -77.4728,
          'nodeNames': [
            'vite-3',
            'vite-full-node'
          ]
        },
        {
          'city': 'Koganei',
          'count': 1,
          'lat': 35.7058,
          'lng': 139.5162,
          'nodeNames': [
            'kyo_vite_node'
          ]
        },
        {
          'city': 'Singapore',
          'count': 77,
          'lat': 1.2931,
          'lng': 103.8558,
          'nodeNames': [
            'wzdo_a_51-239',
            'zz_docm135_10_173',
            'tydo_03_157-38',
            'zz_dohmsf5_55',
            'wzdo_wzz_230-202',
            'zz_dobiv_8_179',
            'zz_dohmsf8_107',
            'wzdo_a_107-226',
            'wzdo_03_113-43',
            'tydo_03_158-22',
            'zz_dobiv_10_79',
            'wzdo_wzz_153-246',
            'zz_dohmsf6_222',
            'zz_dohmsf10_47',
            'tydo_03_156-158',
            'wzdo_a_146-46',
            'wzdo_03_113-29',
            'wzdo_a_83-227',
            'zz_dobiv_1_98_7260a757',
            'zz_dobiv_7_194',
            'zz_dohmsf3_145',
            'wzdo_wzz_182-138',
            'tydo_03_147-111',
            'wzdo_a_16-74',
            'wzdo_a_156-194',
            'zz_docm135_6_46',
            'zz_docm135_1_2_6f3b0493',
            'zz_docm135_2_221',
            'tydo_03_148-218',
            'zz_dobiv_9_155',
            'zz_dobiv_2_184',
            'zz_dobiv_3_64',
            'zz_dobiv_4_50',
            'tydo_03_154-149',
            'zz_docm135_4_136',
            'zz_dohmsf1_106',
            'wzdo_wzz_230-161',
            'zz_docm135_7_23',
            'zz_dohmsf2_212',
            'wzdo_03_126-34',
            'zz_docm135_5_89',
            'tydo_03_156-163',
            'wzdo_a_204-215',
            'tydo_03_144-43',
            'zz_dobiv_5_105',
            'wzdo_a_111-95',
            'wzdo_wzz_230-175',
            'zz_docm135_9_252',
            'alchemy',
            'tydo_03_146-23',
            'zz_docm135_8_226',
            'tydo_03_157-210',
            'wzdo_03_215-107',
            'zz_dohmsf7_163',
            'wzdo_wzz_182-85',
            'zz_dohmsf9_52',
            'wzdo_03_16-88',
            'wzdo_wzz_88-132',
            'asym-sg',
            'wzdo_a_89-238',
            'wzdo_03_124-253',
            'zz_dobiv_6_116',
            'wzdo_03_103-164',
            'zz_dohmsf4_132',
            'wzdo_wzz_182-231',
            'zz_docm135_3_148',
            'wzdo_wzz_190-217',
            'N4Q.org',
            'wzdo_a_45-176',
            'wzdo_03_33-101',
            'wzdo_03_122-148',
            'wzdo_03_113-23',
            'Beautiful-05',
            'Amazing-06',
            'wsc-nl',
            'wsc-us',
            'zz_dofk_2sg_196_7a2c29b3'
          ]
        },
        {
          'city': 'Moscow',
          'count': 12,
          'lat': 55.7522,
          'lng': 37.6156,
          'nodeNames': [
            'ARTvps31a2',
            'ARTvps29a2',
            'ARTvps25a1',
            'ARTvps32a2',
            'ARTvps23a1',
            'ARTvps27a1',
            'ARTvps24a1',
            'ARTvps30a2',
            'ARTvps33a2 ',
            'ARTvps26a1',
            'ARTvps3a3',
            'ARTvps28a2'
          ]
        },
        {
          'city': 'Mumbai',
          'count': 1,
          'lat': 18.975,
          'lng': 72.8258,
          'nodeNames': [
            'vite-8'
          ]
        },
        {
          'city': 'Santa Clara',
          'count': 22,
          'lat': 37.3483,
          'lng': -121.9844,
          'nodeNames': [
            'zz_dovwan_1_93_da1c2215',
            'zz_docmwg68_1_44_cdf7c90e',
            'zz_docmwg684_93',
            'zz_dovwan_10_60',
            'zz_dovwan_8_107',
            'zz_docmwg682_165',
            'zz_dovwan_4_249',
            'zz_docmwg6810_13',
            'zz_dovwan_7_247',
            'zz_dovwan_6_13',
            'zz_docmwg686_21',
            'zz_dovwan_3_233',
            'zz_docmwg683_124',
            'zz_dovwan_5_158',
            'Tricks',
            'zz_docmwg687_201',
            'zz_dovwan_2_95',
            'zz_dovwan_9_47',
            'zz_docmwg688_3',
            'zz_docmwg685_158',
            'zz_docmwg689_231',
            'Beautiful-03'
          ]
        },
        {
          'city': 'Ktis',
          'count': 11,
          'lat': 48.9167,
          'lng': 14.1333,
          'nodeNames': [
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node'
          ]
        },
        {
          'city': 'Amsterdam',
          'count': 7,
          'lat': 52.3529,
          'lng': 4.9415,
          'nodeNames': [
            'steup01',
            'steup02',
            'asym-nl',
            'zz_dofo_1_129_c6805c16',
            'Beautiful-04',
            'Amazing-07',
            'difiga'
          ]
        },
        {
          'city': 'Krasnodar',
          'count': 13,
          'lat': 45.0328,
          'lng': 38.9769,
          'nodeNames': [
            'ARTvps9a4',
            'ARTvps5a3',
            'ARTvps4a3',
            'ARTvps21a6',
            'ARTvps20a6',
            'ARTvps18a6',
            'ARTvps19a6',
            'ARTvps22a1',
            'ARTvps17a6',
            'ARTvps2a3',
            'ARTvps6a3',
            'ARTvps14a5',
            'ARTvps13a5'
          ]
        },
        {
          'city': 'Odesa',
          'count': 1,
          'lat': 46.4775,
          'lng': 30.7326,
          'nodeNames': [
            'Ods1'
          ]
        },
        {
          'city': 'Hamilton',
          'count': 1,
          'lat': -27.439,
          'lng': 153.0629,
          'nodeNames': [
            'vite-full-node-zzt5'
          ]
        },
        {
          'city': 'Kitanagoya',
          'count': 1,
          'lat': 35.2297,
          'lng': 136.8935,
          'nodeNames': [
            'master_vite'
          ]
        },
        {
          'city': 'Vienna',
          'count': 2,
          'lat': 48.164,
          'lng': 16.4463,
          'nodeNames': [
            'luhe01',
            'starman1'
          ]
        },
        {
          'city': 'Yekaterinburg',
          'count': 1,
          'lat': 56.8575,
          'lng': 60.6125,
          'nodeNames': [
            'vite-YuriyK4'
          ]
        },
        {
          'city': 'Nuremberg',
          'count': 8,
          'lat': 49.4075,
          'lng': 11.1649,
          'nodeNames': [
            'vite-Michalis',
            'asym-de',
            'Seele',
            'ViteSG-Node2',
            'Michalis',
            'Mike101',
            'vite-mike',
            'Michalis-vite'
          ]
        },
        {
          'city': 'Dallas',
          'count': 3,
          'lat': 32.9322,
          'lng': -96.8353,
          'nodeNames': [
            'vite-nkat-02',
            'vite-nkat-03',
            'vite-nkat-01'
          ]
        },
        {
          'city': 'Bensalem',
          'count': 1,
          'lat': 40.1109,
          'lng': -74.9378,
          'nodeNames': [
            'trustTheProcess'
          ]
        },
        {
          'city': 'New York',
          'count': 40,
          'lat': 40.7185,
          'lng': -74.0025,
          'nodeNames': [
            'zz_dofo_4_254',
            'zz_docmwg168_4_245',
            'zz_dofo_5_255',
            'zz_dofo_3_253',
            'zz_dofo_8_8',
            'zz_dofo_1_245',
            'zz_docmwg168_10_197',
            'zz_dofo_7_14',
            'zz_dofo_6_10',
            'zz_docmwg168_6_190',
            'zz_docmwg168_7_209',
            'tanuki-09',
            'kitsune-k09',
            'zz_dofo_2_252',
            'zz_docmwg168_8_162',
            'kitsune-k01',
            'kitsune-k06',
            'leodo1',
            'kitsune-k04',
            'kitsune-k05',
            'kitsune-k07',
            'kitsune-k08',
            'vite-Sea60',
            'vite-Sea55',
            'vite-Sea51',
            'vite-Sea68',
            'vite-Sea61',
            'vite-Sea67',
            'vite-Sea52',
            'vite-Sea57',
            'Amazing-10',
            'vite-Sea56',
            'Amazing-03',
            'Beautiful-01',
            'vite-Sea54',
            'vite-Sea66',
            'Amazing-08',
            'vite-Sea64',
            'vite-Sea69',
            'vite-Sea65'
          ]
        },
        {
          'city': 'Sochi',
          'count': 1,
          'lat': 43.6,
          'lng': 39.7303,
          'nodeNames': [
            'rossochi1'
          ]
        },
        {
          'city': 'Volgograd',
          'count': 1,
          'lat': 48.8047,
          'lng': 44.5858,
          'nodeNames': [
            'vite-full-node-vvktk00'
          ]
        },
        {
          'city': 'Los Angeles',
          'count': 5,
          'lat': 34.0494,
          'lng': -118.2641,
          'nodeNames': [
            'N06Pit',
            'Set-7',
            'Hot-5',
            'Set-6',
            'Set-8'
          ]
        },
        {
          'city': 'Sutton Coldfield',
          'count': 1,
          'lat': 52.5879,
          'lng': -1.8128,
          'nodeNames': [
            'ViteMNR1'
          ]
        },
        {
          'city': 'Paris',
          'count': 104,
          'lat': 48.8628,
          'lng': 2.3292,
          'nodeNames': [
            'New-38',
            'cala02',
            'New-37',
            'New-07',
            'VitePhoenix',
            'New-04',
            'cala03',
            'New-39',
            'New-15',
            'New-08',
            'New-36',
            'New-10',
            'New-14',
            'New-02',
            'New-00',
            'nitro-a0caa418',
            'nitro-6e0e1535',
            'nitro-b9c8e857',
            'New-03',
            'New-09',
            'New-12',
            'cala04',
            'vite-full-node',
            'New-06',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'New-35',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'New-34',
            'vite-full-node',
            'vite-full-node',
            'New-24',
            'New-28',
            'vite-full-node',
            'vite-full-node',
            'New-22',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'New-21',
            'vite-full-node',
            'New-20',
            'vite-full-node',
            'New-33',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'New-31',
            'fire-94c9afdd',
            'vite-full-node',
            'New-18',
            'nitro-b9c8e857',
            'nitro-6e0e1535',
            'New-29',
            'vite-full-node',
            'nitro-a0caa418',
            'nitro-fb2ddef8',
            'vite-full-node',
            'vite-full-node',
            'New-13',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'nitro-c4968b58',
            'nitro-48e32123',
            'nitro-0ac7c180',
            'nitro-09415386',
            'nitro-c729bea4',
            'nitro-33246132',
            'nitro-b0b04d71',
            'nitro-614e3612',
            'New-25',
            'nitro-8eecc5ec',
            'vite-full-node',
            '6abcfe30',
            'vite-full-node',
            'New-23',
            'vite-full-node',
            'vite-full-node',
            'vite-full-node',
            'New-26'
          ]
        },
        {
          'city': 'San Mateo',
          'count': 1,
          'lat': 37.5507,
          'lng': -122.3276,
          'nodeNames': [
            'ZVnode'
          ]
        }
      ],
      outerLink: {
        name: this.$t('products.platform.explorer'),
        url: 'https://explorer.vite.net/'
      }
    };
  },
  
};
</script>

<style rel="stylesheet/scss" lang="scss" scoped>
@import "~assets/vars";
  .line {
    display: flex;
    display: -webkit-flex;
    justify-content: space-between;
    margin-top: 70px;
    @include mobile {
      flex-direction: column;
    }
  }
  .card-multi {
    width: 516px;
    height: 375px;
    @include mobile {
      width: 100%;
    }
  }
  .mt {
    @include mobile {
      margin-top: 20px;
    }
  }
  .text__outer-link {
    text-align: center;
    margin-top: 37px;
    font-size:16px;
    font-weight:600;
    color:rgba(0,122,255,1);
    line-height:28px;
  }

</style>

 
